TRANSACTION_LEAVE = 1         # 请假
TRANSACTION_RAISE = 2         # 加薪
TRANSACTION_REIMBURSE = 3     # 报销
TRANSACTION_DIMISSION = 4     # 离职


TRANSACTION_LIST = [
    TRANSACTION_LEAVE,
    TRANSACTION_RAISE,
    TRANSACTION_REIMBURSE,
    TRANSACTION_DIMISSION
]
