# -*- coding: utf-8 -*-
TRANSACTION_LEAVE = 1         # 请假
TRANSACTION_RAISE = 2         # 加薪
TRANSACTION_REIMBURSE = 3     # 报销
TRANSACTION_DIMISSION = 4     # 离职


TRANSACTION_LIST = [
    TRANSACTION_LEAVE,
    TRANSACTION_RAISE,
    TRANSACTION_REIMBURSE,
    TRANSACTION_DIMISSION
]


ZH_TTYPE_DICT = {
    TRANSACTION_LEAVE: u'请假',
    TRANSACTION_RAISE: u'加薪',
    TRANSACTION_REIMBURSE: u'报销',
    TRANSACTION_DIMISSION: u'离职'
}


TRANSACTION_STATUS_CREATE = 1          # 员工刚创建时的状态
TRANSACTION_STATUS_MANAGER = 2          # 本部门经理
TRANSACTION_STATUS_HR = 3               # 人事
TRANSACTION_STATUS_ACCOUNT = 4          # 财务
TRANSACTION_STATUS_HR_MANAGER = 5       # 人事经理
TRANSACTION_STATUS_ACCOUNT_MANAGER = 6  # 财务经理
TRANSACTION_STATUS_GM = 7       # 总经理


TRANSACTION_STATUS_LIST = [
    TRANSACTION_STATUS_CREATE,
    TRANSACTION_STATUS_MANAGER,
    TRANSACTION_STATUS_HR,
    TRANSACTION_STATUS_ACCOUNT,
    TRANSACTION_STATUS_HR_MANAGER,
    TRANSACTION_STATUS_ACCOUNT_MANAGER,
    TRANSACTION_STATUS_HR_MANAGER
]


TRANSACTION_OPERATE_STATUS_CHECK = 1       # 审核中
TRANSACTION_OPERATE_STATUS_HR = 2          # 人事处理中
TRANSACTION_OPERATE_STATUS_ACCOUNT = 3     # 财务处理中
TRANSACTION_OPERATE_STATUS_DONE = 4        # 处理完毕


TRANSACTION_OPERATE_STATUS_LIST = [
    TRANSACTION_OPERATE_STATUS_CHECK,
    TRANSACTION_OPERATE_STATUS_HR,
    TRANSACTION_OPERATE_STATUS_ACCOUNT,
    TRANSACTION_OPERATE_STATUS_DONE
]
